### ISSUE TITLE
Make minium sats for gps fix configurable

### ISSUE THREAD

**Issue by trgFPV** [TobiasBales/PlayuavOSDConfigurator#77]

**Comment by StewLG** [comment]
Right now, that's essentially configurable in ArduPilot, and PlayUAV just respects what ArduPilot is telling it.

Check out these parameters for ArduPilot (http://ardupilot.org/plane/docs/parameters.html#gps-parameters):

EK2_GPS_CHECK
AHRS_GPS_MINSATS

These are some of the values in ArduPilot that control what quality of GPS fix is relayed to PlayUAV via Mavlink. Right now, PlayUAV will not think there is a GPS fix until osd_fix_type < GPS_OK_FIX_3D, out of the following GPS fix types, in ascending order:

NO_GPS
NO_FIX
GPS_OK_FIX_2D
GPS_OK_FIX_3D

(There are fix types beyond this, but they involve exotic RTK stuff we don't deal with in sport flying.)

So, it's up to ArduPilot what a "3D fix" is, and you can try to influence that on the ArduPilot side. 

Although you didn't ask about it directly, it's also important to know that we infer home location as a side effect.  We wait until we are armed, and have a 3D fix, and at that time, we set that as the home location. That generally agrees completely with what ArduPilot does, but it's not perfect - the home location can get moved via Mission Planner or Tower, as well as waypoints, and we would have to continuously poll to figure out if these had changed. Since that's expensive (in bandwidth on the serial line), we don't do it - I've tried.

Generally when I've found myself wanting to cheat the number of minimum sats, it's because I'm getting a low sat count/bad HDOP, and I'm impatient to take off. I eventually gave up on low-quality GPSes and started using somewhat pricey Drotek units instead, and I haven't really had a problem since. 

There are improvements to be made here, but I don't think they should be things where PlayUAV is more optimistic about setting home location than ArduPlane, because then your RTL location may not be where you assume it is. It could be off a low-quality fix location in the nearby woods, rather than where you are actually located.

I hope at least some of this made sense. There are improvements to be made, but I think I'd want to start with improving Mavlink so you could subscribe to changes to home location / waypoints. That would allow us to loosen the linking of arming/home location/fix quality, and control at least some of it in ArduPilot.

**Comment by StewLG** [comment]
Also, this would be a firmware issue strictly speaking, and not a configurator one, but hey, no problem.
