### ISSUE TITLE
Running on windows?

### ISSUE THREAD

**Issue by ABLomas** [TobiasBales/PlayuavOSDConfigurator#78]
Need some documentation how to run configurator on windows (if that's possible - it says "cross-platform", i see linux and osx already supported) - i tried to install node.js, git (i guess python is still missing and some dependencies), but...
When i try to run npm run package - i get several messages about missing modules: http://pastebin.com/Nx1Zd9LT
Guess i need to do something more. Anyone running configurator tool on win?

**Comment by TobiasBales** [comment]
There are some people doing it and it should work.
I am at the moment remodeling it to work as a chrome extension since packaging electron apps is somewhat of a pita.
Should be done this week.
Does that work for you?

Just remembered, realg uploaded a current windows build the other day for some testing http://www18.zippyshare.com/v/RbvLlljT/file.html

All those hoops should not be necessary anymore.

P.S. when using the windows build the binaries will end up in the roaming folder (whyever) and no desktop icon is generated iirc, just so you know

**Comment by ABLomas** [comment]
Works fine, thanks!
Would be great if we can have link to binary available somewhere in wiki, not in issue tracker! =)

**Comment by ABLomas** [comment]
Just home arrow (not radar) position is not configurable (stuck in top-left corner, does not matter which numbers i enter into positional box), but this probably should be opened as separate issue, so this one can be closed.
Thanks.

**Comment by tubeme** [comment]
Hello @TobiasBales do you by any chance have some binaries for windows? The link above has expired long time ago...

Thanks

**Comment by athertop** [comment]
@tubeme, if you search and install the "PlayUAV OSD Configurator" app from the chrome App store, the link in the configurator allows you to download the firmware for the PlayUAVOSD board and flash it from there. Cheers, Paul A

**Comment by tubeme** [comment]
@athertop Thanks I got that already :) Quite handy app. Is there somebody that can take a look at this?

https://github.com/TobiasBales/PlayuavOSD/issues/37

**Comment by StewLG** [comment]
I am closing this issue. To re-iterate, you can download the Chrome app here:

https://chrome.google.com/webstore/detail/playuav-osd-configurator/clledgfbcikcmblfhbkhjeoebioekcnb
